server:
  port: 8080

spring:
  application:
    name: api-repository
  
  # Database
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://172.30.1.9:5432/api_repository
    platform: postgres
    username: lshh
    password: lshh.com
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

# Swagger
management:
  endpoint:
    web:
      exposure:
        include: "*"
        exclude: "env,beans"
        